language: c

git:
  depth: 1

install:
- choco install nasm

script:
- set -e -o pipefail
- export LAME_VERSION="${TRAVIS_TAG:-3.100}"
- wget https://sourceforge.net/projects/lame/files/lame/${LAME_VERSION}/lame-${LAME_VERSION}.tar.gz
- tar -xf lame-${LAME_VERSION}.tar.gz
- cd lame-${LAME_VERSION}
- MSYS_NO_PATHCONV=1 cmd /c ..\\build-libmp3lame.cmd
- cd ..
- mkdir -p stage/lame-${LAME_VERSION}/lib stage/lame-${LAME_VERSION}/include/lame
- cp lame-${LAME_VERSION}/output/* stage/lame-${LAME_VERSION}/lib
- cp lame-${LAME_VERSION}/include/lame.h stage/lame-${LAME_VERSION}/include/lame
- cd stage
- zip -r -9 -v lame-${LAME_VERSION}.zip lame-${LAME_VERSION}

matrix:
  include:
  - os: windows
    name: Win32
    env: TARGET_PLATFORM=x86
  - os: windows
    name: Win64
    env: TARGET_PLATFORM=amd64
